builds:
  - id: "adns"
    main: ./cmd/adns/main.go
    binary: adns

    goos:
      - freebsd
      - windows
      - darwin
      - linux


    goarch:
      - amd64
      - arm
      - arm64
      - "386"

    goarm:
      - 6
      - 7
