builds:
  - id: "adns"
    binary: adns
    main: ./cmd/adns/main.go

    goos:
      - freebsd
      - windows
      - darwin
      - linux


    goarch:
      - amd64
      - arm
      - arm64
      - "386"

    goarm:
      - 6
      - 7
